services:
  actual-budget-csv-importer:
    image: ghcr.io/covenn604/actual-budget-csv-importer:latest
    container_name: actual-budget-csv-importer
    ports:
      - "8080:3000"
    volumes:
      - /mnt/array/appsdata/actual_csv_converter/data:/app/data
      - /mnt/array/appsdata/actual_budget/server.crt:/certs/actual-server.crt:ro
    environment:
      NODE_EXTRA_CA_CERTS: /certs/actual-server.crt
    restart: unless-stopped
